-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "ROOT" SALT '613b8fa956517ef5' HASH '95920ffd2705048ef5d7657becc78127f8f15f5433a088983d854c2136cea9e5' ADMIN;       
CREATE CACHED TABLE "PUBLIC"."PACKINGLIST"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "SEASON" CHARACTER VARYING(255),
    "ITEMS_TEXT" CHARACTER VARYING,
    "JOURNEY_ID" BIGINT
);            
ALTER TABLE "PUBLIC"."PACKINGLIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PACKINGLIST;             
CREATE CACHED TABLE "PUBLIC"."JOURNEY"(
    "ID" BIGINT NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING,
    "STARTDATE" DATE,
    "ENDDATE" DATE,
    "USER_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."JOURNEY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.JOURNEY; 
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT NOT NULL,
    "USERNAME" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
CREATE CACHED TABLE "PUBLIC"."TRAVELLOCATION"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "LATITUDE" DOUBLE PRECISION,
    "LONGITUDE" DOUBLE PRECISION
);         
ALTER TABLE "PUBLIC"."TRAVELLOCATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRAVELLOCATION;          
CREATE CACHED TABLE "PUBLIC"."ENTRY"(
    "ID" BIGINT NOT NULL,
    "TITLE" CHARACTER VARYING(255),
    "TEXT" CHARACTER VARYING,
    "TIMESTAMP" TIMESTAMP,
    "JOURNEY_ID" BIGINT,
    "LOCATION_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ENTRY;   
ALTER TABLE "PUBLIC"."ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F1" FOREIGN KEY("LOCATION_ID") REFERENCES "PUBLIC"."TRAVELLOCATION"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."ENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F" FOREIGN KEY("JOURNEY_ID") REFERENCES "PUBLIC"."JOURNEY"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."PACKINGLIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_69" FOREIGN KEY("JOURNEY_ID") REFERENCES "PUBLIC"."JOURNEY"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."JOURNEY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D6" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;      
